In [9]:
import numpy as np
import time

In [14]:
arr_1d= np.array([1,2,3,4])
print(f"1D Array:{arr_1d}")
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(f"2D Array:{arr_2d}")

1D Array:[1 2 3 4]
2D Array:[[1 2 3 4]
 [5 6 7 8]]


In [13]:
py_list =[1,2,3,4]
print(f"py list multiplication {py_list*2}")

np_array= np.array([1,2,3,4])
print(f"py array multiplication {np_array*2}")


py list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
py array multiplication [2 4 6 8]


In [12]:
start=time.time()
py_list =[i*2 for i in range(100000)]
print(f"list operation time:{time.time()-start}")
start2=time.time()
py_array=np.arange(100000)*2
print(f"array operation time:{time.time()-start2}")



list operation time:0.006819248199462891
array operation time:0.0009608268737792969


====================CREATING ARRAYS BY SCRATCH==================================================================

In [11]:
zeros=np.zeros((3,4))
print(zeros)

ones=np.ones((2,7))
print(ones)

full=np.full((2,15),89)
print(full)

random= np.random.random((6,4))
print(random)

sequence=np.arange(0,14)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[89 89 89 89 89 89 89 89 89 89 89 89 89 89 89]
 [89 89 89 89 89 89 89 89 89 89 89 89 89 89 89]]
[[0.97586808 0.65756266 0.15950352 0.32777965]
 [0.81960121 0.36018274 0.28002567 0.99705325]
 [0.2373231  0.71114234 0.1146287  0.07495466]
 [0.04515909 0.24218383 0.51944244 0.11639122]
 [0.94279075 0.70084998 0.27008206 0.75152607]
 [0.22833249 0.25068945 0.03745929 0.81456179]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


In [15]:
vector=np.array([1,2,3,4])
print(vector)

matrix=np.array([[1,2,3,4],[5,6,7,8]])
print(matrix)

tensor=np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[10,11,12]]])
print(tensor)


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
matrix=np.array([[1,2,3,4],[5,6,7,8.7]])
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype)

(2, 4)
2
8
float64


===============RESHAPING ARRAYS

In [17]:
matrix=np.arange(12)
print(matrix)

reshaped=matrix.reshape(3,4)
print(reshaped)

flattened=reshaped.flatten()
print(flattened)

#transpose of a matrix
reshaped.T

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#=================================NUMPY ARRAY OPERATIONS=================================

In [18]:
array=np.arange(8)
print("Basic slicing:",array[2:7])
print(f"with step:{array[2:8:2]}")
print(f"Negative indexing:{array[1:-1]}")


Basic slicing: [2 3 4 5 6]
with step:[2 4 6]
Negative indexing:[1 2 3 4 5 6]


In [26]:
arr_2d=np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(f"Specific Element:{arr_2d[1,2]}")
print(f"Entire row:{arr_2d[1]}")
print(f"Entire column:{arr_2d[:,1]}")


Specific Element:6
Entire row:[4 5 6]
Entire column:[2 5 8]


In [34]:
unsorted=np.array([2,3,4,2,32,1,43,3])
print(f"Sorted array:{np.sort(unsorted)}")

arr_2d_unsorted=np.array([[1,7],[4,3],[23,5],[24,3]])
print(f"Sorted array by row:\n{np.sort(arr_2d_unsorted)}")
print(f"Sorted array by column:\n{np.sort(arr_2d_unsorted,axis=0)}")


Sorted array:[ 1  2  2  3  3  4 32 43]
Sorted array by row:
[[ 1  7]
 [ 3  4]
 [ 5 23]
 [ 3 24]]
Sorted array by column:
[[ 1  3]
 [ 4  3]
 [23  5]
 [24  7]]


In [ ]:
numbers