In [2]:
import numpy as np
import time

In [19]:
arr_1d= np.array([1,2,3,4])
print(f"1D Array:{arr_1d}")
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(f"2D Array:{arr_2d}")

1D Array:[1 2 3 4]
2D Array:[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
py_list =[1,2,3,4]
print(f"py list multiplication {py_list*2}")

np_array= np.array([1,2,3,4])
print(f"py array multiplication {np_array*2}")


py list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
py array multiplication [2 4 6 8]


In [24]:
start=time.time()
py_list =[i*2 for i in range(100000)]
print(f"list operation time:{time.time()-start}")
start2=time.time()
py_array=np.arange(100000)*2
print(f"array operation time:{time.time()-start2}")



list operation time:0.006585597991943359
array operation time:0.0005562305450439453


====================CREATING ARRAYS BY SCRATCH==================================================================

In [ ]:
zeros=np.zeros((3,4))
print(zeros)

ones=np.ones((2,7))
print(ones)

full=np.full((2,15),89)
print(full)

random= np.random.random((6,4))
print(random)

sequence=np.arange(0,14)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[89 89 89 89 89 89 89 89 89 89 89 89 89 89 89]
 [89 89 89 89 89 89 89 89 89 89 89 89 89 89 89]]
[[0.10241183 0.40596915 0.52476174 0.64798528]
 [0.3597401  0.36266593 0.11551641 0.57216187]
 [0.27421156 0.02160041 0.0833593  0.16431714]
 [0.45134792 0.04348337 0.48148247 0.27922181]
 [0.07414493 0.55292414 0.23084813 0.79052116]
 [0.61502453 0.56309593 0.29876455 0.59888523]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


In [38]:
vector=np.array([1,2,3,4])
print(vector)

matrix=np.array([[1,2,3,4],[5,6,7,8]])
print(matrix)

tensor=np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[10,11,12]]])
print(tensor)


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [43]:
matrix=np.array([[1,2,3,4],[5,6,7,8.7]])
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype)

(2, 4)
2
8
float64


===============RESHAPING ARRAYS

In [48]:
matrix=np.arange(12)
print(matrix)

reshaped=matrix.reshape(3,4)
print(reshaped)

flattened=reshaped.flatten()
print(flattened)

#transpose of a matrix
reshaped.T

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#=================================NUMPY ARRAY OPERATIONS=================================

In [7]:
array=np.arange(8)
print("Basic slicing:",array[2:7])
print(f"with step:{array[2:8:2]}")
print(f"Negative indexing:{array[1:-1]}")


Basic slicing: [2 3 4 5 6]
with step:[2 4 6]
Negative indexing:[1 2 3 4 5 6]
